// =====================================================================
// CUIDA — Banco de Dados de Alimentos
// Valores nutricionais por 100g
// =====================================================================

const FOODS = [

  // ── CARNES E AVES ─────────────────────────────────────────────────
  {n:"Peito de frango desfiado",       c:165, p:31,  ch:0,   g:3.6,  cat:"Carnes e Aves"},
  {n:"Frango grelhado (peito)",         c:165, p:31,  ch:0,   g:3.6,  cat:"Carnes e Aves"},
  {n:"Frango assado (coxa)",            c:215, p:26,  ch:0,   g:12,   cat:"Carnes e Aves"},
  {n:"Frango cozido (coxa s/ pele)",    c:182, p:26,  ch:0,   g:8,    cat:"Carnes e Aves"},
  {n:"Frango ensopado (coxinha da asa)",c:230, p:23,  ch:0,   g:15,   cat:"Carnes e Aves"},
  {n:"Frango frito (empanado)",         c:294, p:23,  ch:10,  g:18,   cat:"Carnes e Aves"},
  {n:"Frango defumado (peito)",         c:160, p:26,  ch:2,   g:5,    cat:"Carnes e Aves"},
  {n:"Frango caipira cozido",           c:190, p:28,  ch:0,   g:8,    cat:"Carnes e Aves"},
  {n:"Peru assado",                     c:189, p:29,  ch:0,   g:7,    cat:"Carnes e Aves"},
  {n:"Peito de peru grelhado",          c:135, p:30,  ch:0,   g:1,    cat:"Carnes e Aves"},
  {n:"Carne bovina (patinho grelhado)", c:219, p:32,  ch:0,   g:9.5,  cat:"Carnes e Aves"},
  {n:"Carne bovina (acém cozido)",      c:250, p:28,  ch:0,   g:14,   cat:"Carnes e Aves"},
  {n:"Picanha grelhada",                c:322, p:27,  ch:0,   g:23,   cat:"Carnes e Aves"},
  {n:"Filé mignon grelhado",            c:200, p:29,  ch:0,   g:9,    cat:"Carnes e Aves"},
  {n:"Alcatra grelhada",                c:214, p:31,  ch:0,   g:9.5,  cat:"Carnes e Aves"},
  {n:"Carne bovina moída refogada",     c:253, p:26,  ch:0,   g:16,   cat:"Carnes e Aves"},
  {n:"Costela bovina assada",           c:291, p:24,  ch:0,   g:21,   cat:"Carnes e Aves"},
  {n:"Cupim assado",                    c:321, p:26,  ch:0,   g:24,   cat:"Carnes e Aves"},
  {n:"Carne seca cozida",               c:250, p:36,  ch:0,   g:10,   cat:"Carnes e Aves"},
  {n:"Carne de cordeiro grelhada",      c:294, p:25,  ch:0,   g:21,   cat:"Carnes e Aves"},
  {n:"Carne de porco (lombo grelhado)", c:215, p:27,  ch:0,   g:11,   cat:"Carnes e Aves"},
  {n:"Linguiça calabresa",              c:330, p:14,  ch:3,   g:29,   cat:"Carnes e Aves"},
  {n:"Salsicha cozida",                 c:301, p:12,  ch:2,   g:27,   cat:"Carnes e Aves"},
  {n:"Bacon",                           c:541, p:37,  ch:1.4, g:42,   cat:"Carnes e Aves"},
  {n:"Presunto cozido",                 c:149, p:18,  ch:1,   g:8,    cat:"Carnes e Aves"},
  {n:"Fígado bovino refogado",          c:175, p:26,  ch:5,   g:5.3,  cat:"Carnes e Aves"},
  {n:"Coração de frango grelhado",      c:185, p:26,  ch:0,   g:9,    cat:"Carnes e Aves"},

  // ── PEIXES E FRUTOS DO MAR ────────────────────────────────────────
  {n:"Salmão grelhado",                 c:208, p:20,  ch:0,   g:13,   cat:"Peixes e Frutos do Mar"},
  {n:"Atum em lata (água)",             c:116, p:26,  ch:0,   g:1,    cat:"Peixes e Frutos do Mar"},
  {n:"Atum em lata (óleo)",             c:198, p:24,  ch:0,   g:11,   cat:"Peixes e Frutos do Mar"},
  {n:"Tilápia grelhada",                c:128, p:26,  ch:0,   g:2.7,  cat:"Peixes e Frutos do Mar"},
  {n:"Sardinha em lata",                c:208, p:25,  ch:0,   g:11,   cat:"Peixes e Frutos do Mar"},
  {n:"Camarão cozido",                  c:99,  p:24,  ch:0,   g:0.3,  cat:"Peixes e Frutos do Mar"},
  {n:"Bacalhau cozido",                 c:160, p:35,  ch:0,   g:1.4,  cat:"Peixes e Frutos do Mar"},
  {n:"Truta grelhada",                  c:190, p:26,  ch:0,   g:9,    cat:"Peixes e Frutos do Mar"},
  {n:"Pescada branca",                  c:105, p:23,  ch:0,   g:1,    cat:"Peixes e Frutos do Mar"},
  {n:"Polvo cozido",                    c:164, p:30,  ch:4,   g:2,    cat:"Peixes e Frutos do Mar"},
  {n:"Lula frita",                      c:175, p:15,  ch:8,   g:9,    cat:"Peixes e Frutos do Mar"},
  {n:"Mexilhão cozido",                 c:172, p:24,  ch:7,   g:4,    cat:"Peixes e Frutos do Mar"},

  // ── OVOS E LATICÍNIOS ─────────────────────────────────────────────
  {n:"Ovo inteiro cozido",              c:155, p:13,  ch:1.1, g:11,   cat:"Ovos e Laticínios"},
  {n:"Clara de ovo",                    c:52,  p:11,  ch:0.7, g:0.2,  cat:"Ovos e Laticínios"},
  {n:"Ovo mexido (s/ manteiga)",        c:148, p:10,  ch:1.6, g:11,   cat:"Ovos e Laticínios"},
  {n:"Leite integral",                  c:61,  p:3.2, ch:4.8, g:3.3,  cat:"Ovos e Laticínios"},
  {n:"Leite desnatado",                 c:35,  p:3.4, ch:5,   g:0.1,  cat:"Ovos e Laticínios"},
  {n:"Leite semidesnatado",             c:46,  p:3.4, ch:5,   g:1.5,  cat:"Ovos e Laticínios"},
  {n:"Iogurte natural",                 c:61,  p:3.5, ch:4.7, g:3.3,  cat:"Ovos e Laticínios"},
  {n:"Iogurte grego integral",          c:97,  p:9,   ch:3.6, g:5,    cat:"Ovos e Laticínios"},
  {n:"Iogurte grego desnatado",         c:59,  p:10,  ch:3.6, g:0.4,  cat:"Ovos e Laticínios"},
  {n:"Queijo mussarela",                c:280, p:22,  ch:2.2, g:22,   cat:"Ovos e Laticínios"},
  {n:"Queijo cottage",                  c:98,  p:11,  ch:3.4, g:4.3,  cat:"Ovos e Laticínios"},
  {n:"Queijo ricota",                   c:174, p:11,  ch:3,   g:13,   cat:"Ovos e Laticínios"},
  {n:"Queijo parmesão",                 c:431, p:38,  ch:4.1, g:29,   cat:"Ovos e Laticínios"},
  {n:"Queijo prato",                    c:352, p:25,  ch:2,   g:27,   cat:"Ovos e Laticínios"},
  {n:"Queijo minas frescal",            c:264, p:17,  ch:3,   g:21,   cat:"Ovos e Laticínios"},
  {n:"Queijo provolone",                c:351, p:26,  ch:2,   g:27,   cat:"Ovos e Laticínios"},
  {n:"Manteiga",                        c:717, p:0.9, ch:0.1, g:81,   cat:"Ovos e Laticínios"},
  {n:"Requeijão cremoso",               c:259, p:9,   ch:3.2, g:23,   cat:"Ovos e Laticínios"},

  // ── CEREAIS E GRÃOS ───────────────────────────────────────────────
  {n:"Arroz branco cozido",             c:130, p:2.7, ch:28,  g:0.3,  cat:"Cereais e Grãos"},
  {n:"Arroz integral cozido",           c:112, p:2.6, ch:23,  g:0.9,  cat:"Cereais e Grãos"},
  {n:"Macarrão cozido",                 c:131, p:5,   ch:25,  g:1.1,  cat:"Cereais e Grãos"},
  {n:"Macarrão integral cozido",        c:124, p:5.3, ch:23,  g:1.4,  cat:"Cereais e Grãos"},
  {n:"Aveia em flocos",                 c:389, p:17,  ch:66,  g:7,    cat:"Cereais e Grãos"},
  {n:"Granola (c/ mel)",                c:471, p:10,  ch:64,  g:20,   cat:"Cereais e Grãos"},
  {n:"Quinoa cozida",                   c:120, p:4.4, ch:21,  g:1.9,  cat:"Cereais e Grãos"},
  {n:"Pão francês",                     c:300, p:9.4, ch:58,  g:3.1,  cat:"Cereais e Grãos"},
  {n:"Pão integral",                    c:247, p:10,  ch:41,  g:5,    cat:"Cereais e Grãos"},
  {n:"Tapioca (hidratada)",             c:250, p:0.2, ch:61,  g:0.2,  cat:"Cereais e Grãos"},
  {n:"Cuscuz de milho",                 c:112, p:2.3, ch:25,  g:0.5,  cat:"Cereais e Grãos"},
  {n:"Cevada cozida",                   c:123, p:2.3, ch:28,  g:0.4,  cat:"Cereais e Grãos"},
  {n:"Milho em flocos",                 c:357, p:8,   ch:79,  g:1.5,  cat:"Cereais e Grãos"},
  {n:"Farinha de trigo",                c:364, p:10,  ch:76,  g:1,    cat:"Cereais e Grãos"},
  {n:"Farinha de milho",                c:365, p:7,   ch:79,  g:3.8,  cat:"Cereais e Grãos"},

  // ── LEGUMINOSAS ───────────────────────────────────────────────────
  {n:"Feijão preto cozido",             c:132, p:8.7, ch:24,  g:0.5,  cat:"Leguminosas"},
  {n:"Feijão carioca cozido",           c:127, p:7.8, ch:22,  g:0.5,  cat:"Leguminosas"},
  {n:"Feijão branco cozido",            c:140, p:9,   ch:25,  g:0.6,  cat:"Leguminosas"},
  {n:"Feijão fradinho cozido",          c:116, p:8,   ch:21,  g:0.5,  cat:"Leguminosas"},
  {n:"Lentilha cozida",                 c:116, p:9,   ch:20,  g:0.4,  cat:"Leguminosas"},
  {n:"Grão-de-bico cozido",             c:164, p:8.9, ch:27,  g:2.6,  cat:"Leguminosas"},
  {n:"Ervilha cozida",                  c:84,  p:5.4, ch:15,  g:0.4,  cat:"Leguminosas"},
  {n:"Soja cozida",                     c:173, p:17,  ch:10,  g:9,    cat:"Leguminosas"},
  {n:"Tofu firme",                      c:76,  p:8,   ch:1.9, g:4.8,  cat:"Leguminosas"},

  // ── VERDURAS E LEGUMES ────────────────────────────────────────────
  {n:"Brócolis cozido",                 c:34,  p:2.8, ch:7,   g:0.4,  cat:"Verduras e Legumes"},
  {n:"Espinafre cru",                   c:23,  p:2.9, ch:3.6, g:0.4,  cat:"Verduras e Legumes"},
  {n:"Cenoura crua",                    c:41,  p:0.9, ch:10,  g:0.2,  cat:"Verduras e Legumes"},
  {n:"Tomate",                          c:18,  p:0.9, ch:3.9, g:0.2,  cat:"Verduras e Legumes"},
  {n:"Cebola crua",                     c:40,  p:1.1, ch:9,   g:0.1,  cat:"Verduras e Legumes"},
  {n:"Abobrinha cozida",                c:17,  p:1.2, ch:3.6, g:0.2,  cat:"Verduras e Legumes"},
  {n:"Pepino",                          c:16,  p:0.7, ch:3.6, g:0.1,  cat:"Verduras e Legumes"},
  {n:"Pimentão vermelho",               c:31,  p:1,   ch:6,   g:0.3,  cat:"Verduras e Legumes"},
  {n:"Milho cozido",                    c:86,  p:3.2, ch:19,  g:1.2,  cat:"Verduras e Legumes"},
  {n:"Cogumelo champignon",             c:22,  p:3.1, ch:3.3, g:0.3,  cat:"Verduras e Legumes"},
  {n:"Alface",                          c:15,  p:1.4, ch:2.9, g:0.2,  cat:"Verduras e Legumes"},
  {n:"Repolho cru",                     c:25,  p:1.3, ch:6,   g:0.1,  cat:"Verduras e Legumes"},
  {n:"Berinjela cozida",                c:35,  p:0.8, ch:9,   g:0.2,  cat:"Verduras e Legumes"},
  {n:"Beterraba cozida",                c:44,  p:1.7, ch:10,  g:0.2,  cat:"Verduras e Legumes"},
  {n:"Alho cru",                        c:149, p:6.4, ch:33,  g:0.5,  cat:"Verduras e Legumes"},
  {n:"Salsa fresca",                    c:36,  p:3,   ch:6,   g:0.8,  cat:"Verduras e Legumes"},

  // ── TUBÉRCULOS ────────────────────────────────────────────────────
  {n:"Batata doce cozida",              c:86,  p:1.6, ch:20,  g:0.1,  cat:"Tubérculos"},
  {n:"Batata inglesa cozida",           c:87,  p:1.9, ch:20,  g:0.1,  cat:"Tubérculos"},
  {n:"Batata frita",                    c:312, p:3.4, ch:41,  g:15,   cat:"Tubérculos"},
  {n:"Mandioca cozida",                 c:125, p:1,   ch:30,  g:0.2,  cat:"Tubérculos"},
  {n:"Inhame cozido",                   c:97,  p:2,   ch:23,  g:0.1,  cat:"Tubérculos"},
  {n:"Cará cozido",                     c:118, p:1.5, ch:28,  g:0.2,  cat:"Tubérculos"},

  // ── FRUTAS ────────────────────────────────────────────────────────
  {n:"Banana prata",                    c:89,  p:1.1, ch:23,  g:0.3,  cat:"Frutas"},
  {n:"Maçã fuji",                       c:52,  p:0.3, ch:14,  g:0.2,  cat:"Frutas"},
  {n:"Laranja pera",                    c:47,  p:0.9, ch:12,  g:0.1,  cat:"Frutas"},
  {n:"Mamão papaia",                    c:43,  p:0.5, ch:11,  g:0.1,  cat:"Frutas"},
  {n:"Melancia",                        c:30,  p:0.6, ch:7.6, g:0.2,  cat:"Frutas"},
  {n:"Manga palmer",                    c:65,  p:0.5, ch:17,  g:0.3,  cat:"Frutas"},
  {n:"Morango",                         c:33,  p:0.7, ch:7.7, g:0.3,  cat:"Frutas"},
  {n:"Abacate",                         c:160, p:2,   ch:9,   g:15,   cat:"Frutas"},
  {n:"Açaí polpa (s/ adição)",          c:58,  p:1.1, ch:5,   g:3.5,  cat:"Frutas"},
  {n:"Uva roxa",                        c:69,  p:0.7, ch:18,  g:0.2,  cat:"Frutas"},
  {n:"Pera",                            c:57,  p:0.4, ch:15,  g:0.1,  cat:"Frutas"},
  {n:"Kiwi",                            c:61,  p:1.1, ch:15,  g:0.5,  cat:"Frutas"},
  {n:"Abacaxi",                         c:50,  p:0.5, ch:13,  g:0.1,  cat:"Frutas"},
  {n:"Coco fresco",                     c:354, p:3.3, ch:15,  g:33,   cat:"Frutas"},
  {n:"Goiaba",                          c:68,  p:2.6, ch:14,  g:1,    cat:"Frutas"},
  {n:"Maracujá",                        c:97,  p:2.2, ch:23,  g:0.7,  cat:"Frutas"},

  // ── OLEAGINOSAS E SEMENTES ────────────────────────────────────────
  {n:"Amendoim torrado s/ sal",         c:567, p:26,  ch:16,  g:49,   cat:"Oleaginosas e Sementes"},
  {n:"Castanha do Pará",                c:656, p:14,  ch:12,  g:66,   cat:"Oleaginosas e Sementes"},
  {n:"Castanha de caju torrada",        c:553, p:18,  ch:33,  g:44,   cat:"Oleaginosas e Sementes"},
  {n:"Nozes",                           c:654, p:15,  ch:14,  g:65,   cat:"Oleaginosas e Sementes"},
  {n:"Amêndoa torrada",                 c:579, p:21,  ch:22,  g:50,   cat:"Oleaginosas e Sementes"},
  {n:"Pistache",                        c:562, p:20,  ch:28,  g:45,   cat:"Oleaginosas e Sementes"},
  {n:"Semente de chia",                 c:486, p:17,  ch:42,  g:31,   cat:"Oleaginosas e Sementes"},
  {n:"Semente de linhaça",              c:534, p:18,  ch:29,  g:42,   cat:"Oleaginosas e Sementes"},
  {n:"Semente de girassol",             c:584, p:21,  ch:20,  g:51,   cat:"Oleaginosas e Sementes"},
  {n:"Pasta de amendoim integral",      c:588, p:25,  ch:20,  g:50,   cat:"Oleaginosas e Sementes"},

  // ── ÓLEOS E GORDURAS ──────────────────────────────────────────────
  {n:"Azeite de oliva extra virgem",    c:884, p:0,   ch:0,   g:100,  cat:"Óleos e Gorduras"},
  {n:"Óleo de coco extra virgem",       c:862, p:0,   ch:0,   g:100,  cat:"Óleos e Gorduras"},
  {n:"Óleo de soja",                    c:884, p:0,   ch:0,   g:100,  cat:"Óleos e Gorduras"},
  {n:"Margarina",                       c:717, p:0.2, ch:0.7, g:81,   cat:"Óleos e Gorduras"},
  {n:"Maionese",                        c:680, p:1.2, ch:3.6, g:75,   cat:"Óleos e Gorduras"},
  {n:"Banha de porco",                  c:902, p:0,   ch:0,   g:100,  cat:"Óleos e Gorduras"},

  // ── SUPLEMENTOS ───────────────────────────────────────────────────
  {n:"Whey Protein concentrado",        c:120, p:24,  ch:3,   g:2,    cat:"Suplementos"},
  {n:"Whey Protein isolado",            c:110, p:27,  ch:1,   g:1,    cat:"Suplementos"},
  {n:"Caseína",                         c:120, p:24,  ch:4,   g:1,    cat:"Suplementos"},
  {n:"Albumina em pó",                  c:357, p:80,  ch:6,   g:1,    cat:"Suplementos"},
  {n:"Barra de proteína (média)",       c:200, p:20,  ch:20,  g:7,    cat:"Suplementos"},
  {n:"Hipercalórico",                   c:390, p:20,  ch:60,  g:5,    cat:"Suplementos"},
  {n:"Creatina",                        c:0,   p:0,   ch:0,   g:0,    cat:"Suplementos"},
  {n:"BCAA",                            c:0,   p:0,   ch:0,   g:0,    cat:"Suplementos"},

  // ── FAST FOOD ─────────────────────────────────────────────────────
  {n:"Hambúrguer (pão + carne + queijo)",c:295,p:17,  ch:24,  g:14,   cat:"Fast Food"},
  {n:"Hot dog",                         c:290, p:11,  ch:24,  g:17,   cat:"Fast Food"},
  {n:"X-Burger",                        c:305, p:17,  ch:30,  g:14,   cat:"Fast Food"},
  {n:"Pizza calabresa (fatia)",         c:285, p:12,  ch:34,  g:12,   cat:"Fast Food"},
  {n:"Pizza de queijo (fatia)",         c:266, p:11,  ch:33,  g:10,   cat:"Fast Food"},
  {n:"Batata frita (porção média)",     c:312, p:3.4, ch:41,  g:15,   cat:"Fast Food"},
  {n:"Chips de batata",                 c:547, p:7,   ch:49,  g:37,   cat:"Fast Food"},
  {n:"Nuggets de frango (6 un)",        c:297, p:16,  ch:17,  g:18,   cat:"Fast Food"},

  // ── DOCES E SOBREMESAS ────────────────────────────────────────────
  {n:"Chocolate amargo 70%",            c:598, p:8,   ch:46,  g:43,   cat:"Doces e Sobremesas"},
  {n:"Chocolate ao leite",              c:535, p:8,   ch:59,  g:30,   cat:"Doces e Sobremesas"},
  {n:"Sorvete de creme",                c:207, p:3.5, ch:24,  g:11,   cat:"Doces e Sobremesas"},
  {n:"Mel de abelha",                   c:304, p:0.3, ch:82,  g:0,    cat:"Doces e Sobremesas"},
  {n:"Açúcar refinado",                 c:387, p:0,   ch:100, g:0,    cat:"Doces e Sobremesas"},
  {n:"Bolo de chocolate",               c:371, p:5,   ch:53,  g:15,   cat:"Doces e Sobremesas"},
  {n:"Bolo de cenoura",                 c:340, p:4,   ch:52,  g:12,   cat:"Doces e Sobremesas"},
  {n:"Brigadeiro",                      c:330, p:4,   ch:45,  g:15,   cat:"Doces e Sobremesas"},
  {n:"Doce de leite",                   c:315, p:6,   ch:55,  g:8,    cat:"Doces e Sobremesas"},

  // ── BEBIDAS ───────────────────────────────────────────────────────
  {n:"Café preto",                      c:2,   p:0.3, ch:0,   g:0,    cat:"Bebidas"},
  {n:"Café com leite",                  c:40,  p:2,   ch:4,   g:1.5,  cat:"Bebidas"},
  {n:"Chá verde",                       c:1,   p:0,   ch:0,   g:0,    cat:"Bebidas"},
  {n:"Suco de laranja natural",         c:45,  p:0.7, ch:10,  g:0.2,  cat:"Bebidas"},
  {n:"Suco de uva",                     c:54,  p:0.3, ch:13,  g:0.1,  cat:"Bebidas"},
  {n:"Suco de abacaxi",                 c:50,  p:0.4, ch:13,  g:0.1,  cat:"Bebidas"},
  {n:"Água de coco",                    c:19,  p:0.7, ch:3.7, g:0.2,  cat:"Bebidas"},
  {n:"Refrigerante cola (350ml)",       c:147, p:0,   ch:38,  g:0,    cat:"Bebidas"},
  {n:"Cerveja (350ml)",                 c:155, p:1.3, ch:13,  g:0,    cat:"Bebidas"},

  // ── PRATOS PRONTOS ────────────────────────────────────────────────
  {n:"Feijoada completa",               c:205, p:12,  ch:15,  g:11,   cat:"Pratos Prontos"},
  {n:"Arroz com feijão",                c:143, p:5.2, ch:27,  g:1.8,  cat:"Pratos Prontos"},
  {n:"Arroz carreteiro",                c:180, p:8,   ch:26,  g:5,    cat:"Pratos Prontos"},
  {n:"Macarronada com carne",           c:190, p:9,   ch:28,  g:6,    cat:"Pratos Prontos"},
  {n:"Frango com arroz",                c:170, p:14,  ch:18,  g:5,    cat:"Pratos Prontos"},
  {n:"Strogonoff de frango",            c:198, p:16,  ch:8,   g:12,   cat:"Pratos Prontos"},
  {n:"Lasanha de carne",                c:190, p:10,  ch:17,  g:9,    cat:"Pratos Prontos"},
  {n:"Purê de batata",                  c:113, p:2,   ch:17,  g:4,    cat:"Pratos Prontos"},

];
